# Generated by Django 4.1.1 on 2022-09-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_userprofile_band_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_band',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True),
        ),
    ]
