# Generated by Django 4.1.1 on 2022-09-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_user_is_band_user_is_organisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicians.band'),
        ),
    ]
