# Generated by Django 4.1.1 on 2022-09-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_alter_musician_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicians.userprofile'),
            preserve_default=False,
        ),
    ]
